"""add attendance entry duration check

Round B fix: attendance_entries had no equivalent of shifts'
``duration_max_24_hours`` CHECK, so a colluding manager+employee could
post an arbitrarily long entry that flows straight into overtime/labor-
cost calculations. Hand-written (not autogenerated) and applied with a
fully-qualified constraint name matching the app's naming convention
exactly (see app/models/attendance_entry.py), verified against
pg_constraint after applying rather than assumed.

Revision ID: 0014_attendance_duration_chk
Revises: 0013_create_audit_logs
Create Date: 2026-08-25 00:00:00.000000

"""
from alembic import op

# revision identifiers, used by Alembic. Kept short: alembic_version.
# version_num is VARCHAR(32), and this project's revision ids double as
# that column's value (see every other file in this directory), so a
# revision id has to actually fit.
revision = '0014_attendance_duration_chk'
down_revision = '0013_create_audit_logs'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "ALTER TABLE attendance_entries ADD CONSTRAINT "
        "ck_attendance_entries_duration_max_24_hours "
        "CHECK (ended_at IS NULL OR ended_at - started_at <= interval '24 hours')"
    )


def downgrade():
    op.drop_constraint(
        'ck_attendance_entries_duration_max_24_hours',
        'attendance_entries',
        type_='check',
    )
