"""location validation config

Revision ID: e8f46c45d41d
Revises: 0017_password_reset_tokens
Create Date: 2026-08-28 13:55:29.611701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018_location_validation'
down_revision = '0017_password_reset_tokens'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_meters', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_job_locations_latitude_range')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_job_locations_longitude_range')),
    sa.CheckConstraint('radius_meters > 0', name=op.f('ck_job_locations_radius_meters_positive')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_job_locations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_locations')),
    sa.UniqueConstraint('id', 'organization_id', name=op.f('uq_job_locations_id'))
    )
    with op.batch_alter_table('attendance_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
        batch_op.create_check_constraint(batch_op.f('ck_attendance_entries_latitude_range'), 'latitude IS NULL OR (latitude >= -90 AND latitude <= 90)')
        batch_op.create_check_constraint(batch_op.f('ck_attendance_entries_location_fields_paired'), '(latitude IS NULL) = (longitude IS NULL)')
        batch_op.create_check_constraint(batch_op.f('ck_attendance_entries_longitude_range'), 'longitude IS NULL OR (longitude >= -180 AND longitude <= 180)')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
        batch_op.add_column(sa.Column('radius_meters', sa.BigInteger(), nullable=True))
        batch_op.create_check_constraint(batch_op.f('ck_departments_latitude_range'), 'latitude IS NULL OR (latitude >= -90 AND latitude <= 90)')
        batch_op.create_check_constraint(batch_op.f('ck_departments_location_fields_paired'), '(latitude IS NULL) = (longitude IS NULL) AND (latitude IS NULL) = (radius_meters IS NULL)')
        batch_op.create_check_constraint(batch_op.f('ck_departments_longitude_range'), 'longitude IS NULL OR (longitude >= -180 AND longitude <= 180)')
        batch_op.create_check_constraint(batch_op.f('ck_departments_radius_meters_positive'), 'radius_meters IS NULL OR radius_meters > 0')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_validation_mode', sa.Text(), server_default='NONE', nullable=False))
        batch_op.create_check_constraint(batch_op.f('ck_organizations_location_validation_mode_valid'), "location_validation_mode IN ('NONE', 'FIXED_SITE', 'MULTI_SITE', 'MOBILE', 'SHIFT_JOB_LOCATION')")

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_location_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shifts_job_location_id_job_locations'), 'job_locations', ['job_location_id', 'organization_id'], ['id', 'organization_id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shifts_job_location_id_job_locations'), type_='foreignkey')
        batch_op.drop_column('job_location_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_organizations_location_validation_mode_valid'), type_='check')
        batch_op.drop_column('location_validation_mode')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_departments_radius_meters_positive'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_departments_longitude_range'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_departments_location_fields_paired'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_departments_latitude_range'), type_='check')
        batch_op.drop_column('radius_meters')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('attendance_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ck_attendance_entries_longitude_range'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_attendance_entries_location_fields_paired'), type_='check')
        batch_op.drop_constraint(batch_op.f('ck_attendance_entries_latitude_range'), type_='check')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.drop_table('job_locations')
    # ### end Alembic commands ###
